[base]
a = [1,0,0,0,
     0,0,0,0]
b = [0,0,0,0,
     1,0,0,1]
c = [0,0,0,0,
     1,1,0,0]
d = [1,1,1,0,
     0,0,0,0]
e = [0,0,0,0,
     1,0,0,0]
f = [1,1,0,0,
     0,0,0,0]
g = [0,1,1,0,
     0,0,0,0]
h = [0,0,0,0,
     1,0,1,0]
i = [0,0,0,0,
     0,0,1,0]
j = [0,0,1,1,
     0,0,0,0]
k = [0,0,0,0,
     0,1,0,1]
l = [0,0,0,0,
     1,1,1,0]
m = [0,0,0,0,
     0,1,1,1]
n = [0,0,0,0,
     0,0,1,1]
o = [0,0,0,0,
     0,0,0,1]
p = [0,0,0,0,
     1,0,1,1]
q = [1,0,1,1,
     0,0,0,0]
r = [0,1,0,0,
     0,0,0,0]
s = [0,0,0,1,
     0,0,0,0]
t = [0,0,1,0,
     0,0,0,0]
u = [0,0,0,0,
     0,1,1,0]
v = [0,1,0,1,
     0,0,0,0]
w = [1,0,0,1,
     0,0,0,0]
x = [0,1,1,1,
     0,0,0,0]
y = [0,0,0,0,
     0,1,0,0]
z = [1,1,1,1,
     0,0,0,0]

"," = [1,0,0,0,
       0,1,0,0]
"." = [1,0,0,0,
       0,0,1,0]
"/" = [1,0,0,0,
       0,0,0,1]
"'" = [0,1,0,0,
       0,1,0,0]
"!" = [0,0,1,0,
       0,0,1,0]
"?" = [0,0,0,1,
       0,0,0,1]

" " = [0,0,0,0,
       1,1,1,1]
backspace = [0,1,0,0,
             1,0,0,0]
delete = [0,1,0,0,
          0,0,1,0]
enter = [1,0,0,0,
         1,0,0,0]
esc = [1,1,0,0,
       0,0,0,1]
tab = [1,1,1,0,
       0,0,0,1]
shift = [0,1,1,1,
        1,0,0,0]

# todo add brackets, numbers, symbols and media
# I have to first remember all of the above though :)

[toggle]
ctrl = [0,0,0,1,
        1,0,0,0]
gui =  [0,0,0,1,
        0,1,0,0]
alt =  [0,0,0,1,
        0,0,1,0]
shift = [1,0,0,0,
        0,1,1,1]
clear = [1,1,1,1,
        1,1,1,1]

[layers]
mouse = [1,0,1,0,
         0,1,0,0]
nav =   [0,1,0,0,
         1,0,1,0]

[mouse]

[nav]
